version: "3.7"

services:
  db:
    image: postgis/postgis:13-3.2-alpine
    volumes:
      - /docker/db:/var/lib/postgres/data/pgdata
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "
      ./wait-for db:5432 &&
      python ./manage.py migrate &&
      python ./manage.py defaultadmin &&
      gunicorn --timeout 300 config.wsgi:application -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./public/static:/app/public/static
      - ./public/media:/app/public/media
      - ./private/logs:/app/private/logs
      - ./.env:/app/.env
    restart: always
    depends_on:
      - db

  # nginx:
  #   image: nginx:1.17.6-alpine
  #   volumes:
  #     - ./public/static:/var/www/app/public/static
  #     - ./public/media:/var/www/app/public/media
  #     - ./private/logs:/var/www/app/private/logs
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./robots.txt:/etc/nginx/conf.d/robots.txt
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - app
