version: "3.7"

services:
  db:
    image: postgis/postgis:13-3.2-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "
      ./wait-for db:5432 &&
      poetry run task collectstatic --clear &&
      poetry run task migrate &&
      poetry run task defaultadmin &&
      poetry run task defaultfixtures &&
      poetry run task gunicorn"
    ports:
      - 8000:8000
    volumes:
      - ./.env:/var/www/app/.env
      - static:/var/www/app/public/static
      - media:/var/www/app/public/media
      - logs:/var/www/app/public/logs
    restart: always
    depends_on:
      - db

  nginx:
    image: nginx:1.17.6-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static:/var/www/app/public/static
      - media:/var/www/app/public/media
      - logs:/var/www/app/public/logs
    restart: always
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  static:
  media:
  pg-data:
  logs:
