# Generated by Django 3.2.11 on 2022-01-24 17:29

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CreateExtension("postgis"),
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        null=True, srid=4326, verbose_name="Координаты"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=500, null=True, verbose_name="Адрес"
                    ),
                ),
            ],
            options={
                "verbose_name": "Здание",
                "verbose_name_plural": "Здания",
            },
        ),
    ]
