# Generated by Django 3.2.11 on 2022-01-23 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Здание', 'verbose_name_plural': 'Здания'},
        ),
    ]
