# Generated by Django 3.2.11 on 2022-01-24 15:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_map', '0002_alter_building_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326, verbose_name='Координаты'),
        ),
    ]
